### ISSUE TITLE
MultiSliver inside SingleChildScrollView: SliverGeometry is not valid: The "cacheExtent" is negative.

### ISSUE THREAD

**Issue by dkbast** [Kavantix/sliver_tools#54]
I have a CustomScrollView which needs to be recycled in another part of the app where it is used inside a SingleChildScrollView - in my production app this works as long as I don't have any MultiSliver widgets in the tree (which I use to add sticky headers to categories which are SliverLists).

Code to reproduce the issue: 
https://github.com/dkbast/multi_sliver_bug_repro/blob/main/lib/main.dart

It looks like in this minimal example the version without a MultiSliver is also failing - this might be due to all widgets being in the same build function, as it is working for me on the other project. 

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
SliverGeometry is not valid: The "cacheExtent" is negative.
The RenderSliver that returned the offending geometry was: RenderMultiSliver#6fcfe relayoutBoundary=up27 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
  creator: MultiSliver ← ShrinkWrappingViewport ← IgnorePointer-[GlobalKey#5bf37] ← Semantics ←
    Listener ← _GestureSemantics ←
    RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#958af] ← Listener ← _ScrollableScope
    ← _ScrollSemantics-[GlobalKey#543dc] ← NotificationListener<ScrollMetricsNotification> ←
    RepaintBoundary ← ⋯
  parentData: layoutOffset=None (can use size)
  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle,
    scrollOffset: 0.0, remainingPaintExtent: Infinity, crossAxisExtent: 800.0, crossAxisDirection:
    AxisDirection.right, viewportMainAxisExtent: Infinity, remainingCacheExtent: Infinity,
    cacheOrigin: -0.0)
  geometry: SliverGeometry(scrollExtent: 580.0, paintExtent: 580.0, maxPaintExtent: 580.0,
    cacheExtent: NaN)

The relevant error-causing widget was:
  MultiSliver
  MultiSliver:file:///Users/damianbast/src/github.com/dkbast/multi_sliver_bug_repro/lib/main.dart:80:13

When the exception was thrown, this was the stack:
#0      SliverGeometry.debugAssertIsValid.<anonymous closure>.verify (package:flutter/src/rendering/sliver.dart:709:9)
#1      SliverGeometry.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/sliver.dart:724:7)
#2      SliverGeometry.debugAssertIsValid (package:flutter/src/rendering/sliver.dart:748:6)
#3      RenderSliver.debugAssertDoesMeetConstraints (package:flutter/src/rendering/sliver.dart:1200:22)
#4      RenderObject.layout.<anonymous closure> (package:flutter/src/rendering/object.dart:1918:9)
#5      RenderObject.layout (package:flutter/src/rendering/object.dart:1920:8)
#6      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510:13)
#7      RenderShrinkWrappingViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1938:12)
#8      RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1884:20)
#9      RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#10     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#11     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#12     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#13     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#14     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#15     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#16     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#17     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#18     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#19     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#20     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#21     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#22     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#23     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#25     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545:11)
#26     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#28     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#30     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#32     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#34     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#35     _RenderSingleChildViewport.performLayout (package:flutter/src/widgets/single_child_scroll_view.dart:513:14)
#36     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#37     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#38     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#39     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#40     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#41     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#42     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#43     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#44     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#45     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#46     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#47     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#48     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#49     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#50     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#51     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#52     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545:11)
#53     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#54     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#55     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#56     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#57     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#58     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#59     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#60     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#61     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#62     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#63     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1003:7)
#64     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
#65     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
#66     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#67     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#68     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#69     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#70     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1376:11)
#71     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#72     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#73     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#74     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#75     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#76     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#77     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#78     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#79     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:552:43)
#80     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:579:12)
#81     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#82     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#83     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#84     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#85     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#86     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#87     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#88     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#89     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#90     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#91     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#92     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#93     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#94     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3460:14)
#95     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#96     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#97     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#98     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:749:15)
#99     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1757:7)
#100    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
#101    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:504:19)
#102    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:892:13)
#103    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#104    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#105    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#106    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
#110    _invoke (dart:ui/hooks.dart:151:10)
#111    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#112    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)

The following RenderObject was being processed when the exception was fired: RenderMultiSliver#6fcfe relayoutBoundary=up27 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
  creator: MultiSliver ← ShrinkWrappingViewport ← IgnorePointer-[GlobalKey#5bf37] ← Semantics ←
    Listener ← _GestureSemantics ←
    RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#958af] ← Listener ← _ScrollableScope
    ← _ScrollSemantics-[GlobalKey#543dc] ← NotificationListener<ScrollMetricsNotification> ←
    RepaintBoundary ← ⋯
  parentData: layoutOffset=None (can use size)
  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle,
    scrollOffset: 0.0, remainingPaintExtent: Infinity, crossAxisExtent: 800.0, crossAxisDirection:
    AxisDirection.right, viewportMainAxisExtent: Infinity, remainingCacheExtent: Infinity,
    cacheOrigin: -0.0)
  geometry: SliverGeometry(scrollExtent: 580.0, paintExtent: 580.0, maxPaintExtent: 580.0,
    cacheExtent: NaN)
This RenderObject had the following descendants (showing up to depth 5):
    child 1: RenderSliverToBoxAdapter#68df9 relayoutBoundary=up28 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
      child: RenderConstrainedBox#abb2e relayoutBoundary=up29 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        child: _RenderColoredBox#b79bb NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
          child: RenderLimitedBox#29420 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            child: RenderConstrainedBox#e8c02 NEEDS-PAINT
    child 2: RenderSliverList#d2cc2 relayoutBoundary=up28 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
      child with index 0: RenderIndexedSemantics#11826 relayoutBoundary=up29 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        child: RenderRepaintBoundary#c3a53 relayoutBoundary=up30 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
          child: RenderSemanticsAnnotations#d8f9e relayoutBoundary=up31 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            child: RenderMouseRegion#af3ca relayoutBoundary=up32 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
      child with index 1: RenderIndexedSemantics#24d37 relayoutBoundary=up29 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        child: RenderRepaintBoundary#80f51 relayoutBoundary=up30 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
          child: RenderSemanticsAnnotations#dc001 relayoutBoundary=up31 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            child: RenderMouseRegion#4d6cb relayoutBoundary=up32 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
      child with index 2: RenderIndexedSemantics#24660 relayoutBoundary=up29 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        child: RenderRepaintBoundary#e5124 relayoutBoundary=up30 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
          child: RenderSemanticsAnnotations#f3a3d relayoutBoundary=up31 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            child: RenderMouseRegion#e1bac relayoutBoundary=up32 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
      child with index 3: RenderIndexedSemantics#1b9df relayoutBoundary=up29 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        child: RenderRepaintBoundary#1fca4 relayoutBoundary=up30 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
          child: RenderSemanticsAnnotations#7763f relayoutBoundary=up31 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            child: RenderMouseRegion#1b069 relayoutBoundary=up32 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
      child with index 4: RenderIndexedSemantics#25e10 relayoutBoundary=up29 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        child: RenderRepaintBoundary#59889 relayoutBoundary=up30 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
          child: RenderSemanticsAnnotations#31b90 relayoutBoundary=up31 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            child: RenderMouseRegion#25270 relayoutBoundary=up32 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
    ...(descendants list truncated after 25 lines)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by Kavantix** [comment]
After discussing this a bit offline the root cause it that the CustomScrollView is not constrained in height, it's still up for debate whether or not MultiSliver should support this.
Putting this on low prio for now.

Anyone running into this, please comment here and we can see what can be done.
